// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhT4refXk78ESm3Pv5mTFFD8NuNW7iRqI',
    appId: '1:316612406091:android:6feb0987bccadbc2f916ce',
    messagingSenderId: '316612406091',
    projectId: 'fir-analytics-e4d3a',
    databaseURL: 'https://fir-analytics-e4d3a.firebaseio.com',
    storageBucket: 'fir-analytics-e4d3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5kPX4AxTddIdEG6S7DiqNGa3ELtmXT0U',
    appId: '1:316612406091:ios:421f8b25235792ddf916ce',
    messagingSenderId: '316612406091',
    projectId: 'fir-analytics-e4d3a',
    databaseURL: 'https://fir-analytics-e4d3a.firebaseio.com',
    storageBucket: 'fir-analytics-e4d3a.appspot.com',
    androidClientId: '316612406091-10oc78nhmgrujeq526m508nbbor2k6ij.apps.googleusercontent.com',
    iosClientId: '316612406091-0mkglpn9tbcngbqjoq8gojko3ahgo23c.apps.googleusercontent.com',
    iosBundleId: 'com.jjins.shoppingmallflutter.shoppingmallflutter',
  );
}
